name: Build and Release

on:
  push:
    branches: [main]
    paths:
      - "dev.html"
      - "style.css"
      - "script.js"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Just
        uses: extractions/setup-just@v1

      - name: Build index.html
        run: just

      - name: Format index.html
        run: npx prettier --write index.html

      - name: Rename to release.html
        run: mv index.html release.html

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          name: Release ${{ github.run_number }}
          files: release.html
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
